# Generated by Django 4.0.3 on 2023-11-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
