# Generated by Django 4.2.7 on 2023-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_book_bookid"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ebook",
            field=models.FileField(blank=True, null=True, upload_to="ebooks/"),
        ),
    ]
