# Generated by Django 4.2.7 on 2023-11-09 09:35

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_book_ebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ebook",
            field=models.FileField(
                blank=True, null=True, upload_to=catalog.models.Book.upload_path
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="number_of_copies",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="number_of_copies_available",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(
                        models.PositiveIntegerField(default=0)
                    )
                ],
            ),
        ),
    ]
