# Generated by Django 4.2.3 on 2023-11-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="issuedbooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollnumber", models.CharField(max_length=100)),
                ("number_of_copies", models.IntegerField()),
                ("reason_for_issue", models.TextField()),
                ("date_of_issue", models.DateField(default=datetime.date(2023, 11, 8))),
                ("date_of_submission", models.DateField()),
            ],
        ),
    ]
