# Generated by Django 4.2.3 on 2023-11-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedbooks",
            name="bookid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issuedbooks",
            name="date_of_issue",
            field=models.DateField(default=datetime.date(2023, 11, 9)),
        ),
    ]
